### ISSUE TITLE
Syntax errors in the current release

### ISSUE THREAD

**Issue by jamesbernardi** [ansible-lockdown/AMAZON2-CIS#25]
There seem to be serveral syntax errors in the latest release causing the ansible script to abort

```
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/srv/ansible/handlers/main.yml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: sysctl flush ipv6 route table
  ^ here
```

And If I remove those sections I get:

```
ERROR! couldn't resolve module/action 'modprobe'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/srv/ansible/tasks/section_1/cis_1.1.1.x.yml': line 13, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Remove cramfs module"
        ^ here
```

**Control(s) Affected**
All - the script will not complete 

**Environment (please complete the following information):**
 - Ansible Version: [e.g. 2.10] 
 - Host Python Version: [e.g. Python 3.7.6]
 - Ansible Server Python Version: [e.g. Python 3.7.6]
 - branch: [e.g. devel]
 - Additional Details:

**Comment by uk-bolly** [comment]
Hi @jamesbernardi 

Looking at the changes we didn't adjust the way those tasks change in the latest release, it was purely to remove the older vars: warn set on some controls, stopping it from working ion later releases.

Both of the examples you have provided require non ansible-core modules from collections to be available, the collections are required to be on the system and can be found in the collections/requirements file.
Depending on the version of ansible you are using you may need to either install manually or stipulate the github repository in order to use the latest ansible-galaxy commands to get these collections on your system.
More information can be found here https://docs.ansible.com/ansible/latest/collections_guide/index.html
I hope that makes sense and helps to resolve your question?

FYI

We are looking to release v3 (a rewrite due to the number of changes) in the next couple of months that should resolve all of this (its already written and in private repository for subscribers early access).

I hope that helps.

uk-bolly
